### ISSUE TITLE
App crashed!

### ISSUE THREAD

**Issue by amitmerchant1990** [kishorm23/WiFiSharer#1]
Hi Kishor,

I have installed your app in my Samsung Galaxy Y. And after installing it no wonder ehy my phone got restarted. Kindly look into this issue.

Thanks!

**Comment by kishorm23** [comment]
Thanks for testing. Could you please paste the logcat output here that will help me to find out the issue. Also does phone gets restarted every time you open the app or app works normally after a restart?
